#ifndef SPO_LAB3_ERROR_H
#define SPO_LAB3_ERROR_H

#define SUCCESS 0
#define ERROR_SERVER_SOCKET_OPEN 1
#define ERROR_SERVER_SOCKET_SET_NAME 2
#define ERROR_SERVER_SOCKET_BIND 3
#define ERROR_SERVER_SOCKET_LISTEN 4
#define ERROR_SERVER_ACCEPT 5
#define ERROR_SERVER_SEND_BOOK 6
#define ERROR_CLIENT_OPEN_SOCKET 7
#define ERROR_CLIENT_CONNECT 8
#define ERROR_CLIENT_CONNECT_SERVER 9
#define ERROR_CLIENT_TERMINAL_ERRPR 10

#define ERROR_MESSAGE_SOCKET_OPEN "socket_open failed"
#define ERROR_MESSAGE_SOCKET_SET_NAME "socket_set_name failed"
#define ERROR_MESSAGE_SOCKET_BIND "socket_bind failed"
#define ERROR_MESSAGE_SOCKET_LISTEN "socket_listen failed"
#define ERROR_MESSAGE_SOCKET_CONNECT "socket_connect failed"

#endif //SPO_LAB3_ERROR_H
